GyroAccGlove: HardwareSerial.cpp File Reference
HardwareSerial.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include "HardwareSerial.h"
Classes
struct ring_buffer
Defines
#define RX_BUFFER_SIZE 128
#define SERIAL_ISR_DEF(usart)
Functions
SERIAL_ISR_DEF (USARTC0)
SERIAL_ISR_DEF (USARTC1)
SERIAL_ISR_DEF (USARTD0)
SERIAL_ISR_DEF (USARTD1)
SERIAL_ISR_DEF (USARTE0)
SERIAL_ISR_DEF (USARTE1)
SERIAL_ISR_DEF (USARTF0)
void store_char (unsigned char c, ring_buffer *rx_buffer)
static void SetPointer (USART_t *usart, HardwareSerial *p)
Define Documentation
#define RX_BUFFER_SIZE 128
Definition at line 14 of file HardwareSerial.cpp.
Referenced by HardwareSerial::available(), HardwareSerial::HardwareSerial(), HardwareSerial::read(), and store_char().
#define SERIAL_ISR_DEF (usart)
Value:
static HardwareSerial*  usart##cp = 0;\
ISR(usart##_RXC_vect) {\
    if (usart##cp) usart##cp->rxc();\
}\
ISR(usart##_DRE_vect) {\
    if (usart##cp) usart##cp->dre();\
}\
ISR(usart##_TXC_vect) {\
    if (usart##cp) usart##cp->txc();\
}
Definition at line 24 of file HardwareSerial.cpp.
Function Documentation
SERIAL_ISR_DEF (USARTC0)
SERIAL_ISR_DEF (USARTC1)
SERIAL_ISR_DEF (USARTD1)
SERIAL_ISR_DEF (USARTF0)
SERIAL_ISR_DEF (USARTE1)
SERIAL_ISR_DEF (USARTE0)
SERIAL_ISR_DEF (USARTD0)
static void SetPointer (USART_t * usart, HardwareSerial * p) [static]
Definition at line 61 of file HardwareSerial.cpp.
Referenced by HardwareSerial::begin2x(), HardwareSerial::end(), HardwareSerial::HardwareSerial(), TimerCntr::TimerCntr(), HardwareSerial::~HardwareSerial(), and TimerCntr::~TimerCntr().
{
    // Register this object with the appropriate
    // pointer so that the ISR routines can call p
    // class.
    if(usart == &USARTC0) {
        USARTC0cp = p;
    } else if (usart == &USARTC1) {
        USARTC1cp = p;
    } else if (usart ==  &USARTD0) {
        USARTD0cp = p;
    } else if (usart ==  &USARTD1) {
        USARTD1cp = p;
    } else if (usart ==  &USARTE0) {
        USARTE0cp = p;
    } else if (usart ==  &USARTE1) {
        USARTE1cp = p;
    } else if (usart ==  &USARTF0) {
        USARTF0cp = p;
#if defined(USARTF1_RXC_vect)
    } else if (usart ==  &USARTF1) {
        USARTF1cp = p;
#endif
    }
}
void store_char (unsigned char c, ring_buffer * rx_buffer) [inline]
Definition at line 47 of file HardwareSerial.cpp.
References ring_buffer::buffer, ring_buffer::head, RX_BUFFER_SIZE, and ring_buffer::tail.
Referenced by HardwareSerial::rxc().
{
    int i = (rx_buffer->head + 1) % RX_BUFFER_SIZE;
    // if we should be storing the received character into the location
    // just before the tail (meaning that the head would advance to the
    // current location of the tail), we're about to overflow the buffer
    // and so we don't write the character or advance the head.
    if (i != rx_buffer->tail) {
        rx_buffer->buffer[rx_buffer->head] = c;
        rx_buffer->head = i;
    }
}