GyroAccGlove: I2C_Master Class Reference
I2C_Master Class Reference
#include <I2C_Master.h>
Public Types
enum DriverState {
sIdle, sBusy, sError, sArb,
sIDScan, sIDCheck
}
enum DriverResult {
rOk, rFail, rArbLost, rBussErr,
rNack, rBufferOverrun, rUnknown, rTimeout
}
enum ErrorType {
eNone = 0, eDisabled = -1, eBusy = -2, eNack = -3,
eArbLost = -4, eBusErr = -5, eTimeout = -6, eSDAStuck = -7,
eSCLStuck = -8, eUnknown = -9
}
typedef enum I2C_Master::ErrorType ErrorType
Public Member Functions
I2C_Master (TWI_t *twi)
~I2C_Master ()
void begin (uint32_t freq)
void end ()
ErrorType Write (uint8_t ID, uint8_t *Data, uint8_t nBytes)
ErrorType WriteSync (uint8_t ID, uint8_t *Data, uint8_t nBytes)
ErrorType Read (uint8_t ID, uint8_t nBytes)
ErrorType ReadSync (uint8_t ID, uint8_t nBytes)
ErrorType WriteRead (uint8_t ID, uint8_t *wrData, uint8_t nWriteBytes, uint8_t nReadBytes)
ErrorType WriteReadSync (uint8_t ID, uint8_t *wrData, uint8_t nWriteBytes, uint8_t nReadBytes)
void master_int ()
void slave_int ()
void WriteHandler ()
void ReadHandler ()
void ArbHandler ()
void ErrorHandler ()
void MasterFinished ()
int testack (uint8_t ID)
void dumpregs ()
I2C_Master::DriverResult Result ()
I2C_Master::DriverState State ()
uint8_t ReadData (uint8_t *pData, uint8_t maxcnt)
uint8_t ReadData (uint8_t index)
uint8_t nReadBytes ()
ErrorType CheckID (uint8_t ID)
void Stop ()
ErrorType ForceStartStop ()
ErrorType WigglePin (uint8_t cnt, uint8_t pinSel, uint8_t otherState)
void CleanRegs ()
void loop ()
bool busy ()
void * isReserved ()
bool Reserve (void *)
void NotifyMe (I2CNotify *pMe)
bool IsIdle ()
Protected Member Functions
uint8_t busState ()
void showstate ()
Private Attributes
TWI_t * _twi
PORT_t * _twiPort
bool _bEnabled
DriverState _State
DriverResult _Result
void * _pReserved
I2CNotify * _pNotifyClient
uint8_t _DeviceID
uint8_t _nBytesWritten
uint8_t _nWriteBytes
uint8_t _nReadBytes
uint8_t _nBytesRead
uint8_t * _WriteData
uint8_t _wrBufferLen
uint8_t * _ReadData
uint8_t _rdBufferLen
uint8_t _idScanCurrent
uint8_t _IDList [128]
bool _ScanComplete
Detailed Description
Definition at line 25 of file I2C_Master.h.
Member Typedef Documentation
typedef enum I2C_Master::ErrorType I2C_Master::ErrorType
Member Enumeration Documentation
enum I2C_Master::DriverResult
Enumerator:
rOk
rFail
rArbLost
rBussErr
rNack
rBufferOverrun
rUnknown
rTimeout
Definition at line 37 of file I2C_Master.h.
                 {
        rOk,
        rFail,
        rArbLost,
        rBussErr,
        rNack,
        rBufferOverrun,
        rUnknown,
        rTimeout
    } DriverResult;
enum I2C_Master::DriverState
Enumerator:
sIdle
sBusy
sError
sArb
sIDScan
sIDCheck
Definition at line 28 of file I2C_Master.h.
                 {
        sIdle,
        sBusy,
        sError,
        sArb,
        sIDScan,
        sIDCheck
    } DriverState;
enum I2C_Master::ErrorType
Enumerator:
eNone
eDisabled
eBusy
eNack
eArbLost
eBusErr
eTimeout
eSDAStuck
eSCLStuck
eUnknown
Definition at line 78 of file I2C_Master.h.
{
        eNone           = 0,
        eDisabled       = -1,
        eBusy           = -2,
        eNack           = -3,
        eArbLost        = -4,
        eBusErr         = -5,
        eTimeout        = -6,
        eSDAStuck       = -7,
        eSCLStuck       = -8,
        eUnknown        = -9
    } ErrorType;
Constructor & Destructor Documentation
I2C_Master::I2C_Master (TWI_t * twi)
I2C_Master::~I2C_Master ()
Member Function Documentation
void I2C_Master::ArbHandler ()
void I2C_Master::begin (uint32_t freq)
Referenced by main(), and IMU::Reset().
uint8_t I2C_Master::busState () [protected]
bool I2C_Master::busy ()
Referenced by IMU::Run().
ErrorType I2C_Master::CheckID (uint8_t ID)
Referenced by IMU::CheckIDs(), and IMU::QueryChannels().
void I2C_Master::CleanRegs ()
void I2C_Master::dumpregs ()
void I2C_Master::end ()
Referenced by IMU::Reset().
void I2C_Master::ErrorHandler ()
ErrorType I2C_Master::ForceStartStop ()
Referenced by IMU::ForceStartStop().
bool I2C_Master::IsIdle () [inline]
Definition at line 153 of file I2C_Master.h.
References _twi.
    {
        return (_twi->MASTER.STATUS & TWI_MASTER_BUSSTATE_gm)
            == TWI_MASTER_BUSSTATE_IDLE_gc;
    }
void* I2C_Master::isReserved ()
void I2C_Master::loop ()
void I2C_Master::master_int ()
void I2C_Master::MasterFinished ()
void I2C_Master::NotifyMe (I2CNotify * pMe)
Referenced by IMU::IMU(), and IMU::Reset().
uint8_t I2C_Master::nReadBytes ()
ErrorType I2C_Master::Read (uint8_t ID, uint8_t nBytes)
uint8_t I2C_Master::ReadData (uint8_t * pData, uint8_t maxcnt)
Referenced by IMU::Rd(), IMU::ReadWord(), IMU::StoreAccData(), and IMU::StoreGyroData().
uint8_t I2C_Master::ReadData (uint8_t index)
void I2C_Master::ReadHandler ()
ErrorType I2C_Master::ReadSync (uint8_t ID, uint8_t nBytes)
bool I2C_Master::Reserve (void *)
I2C_Master::DriverResult I2C_Master::Result ()
void I2C_Master::showstate () [protected]
void I2C_Master::slave_int ()
I2C_Master::DriverState I2C_Master::State ()
void I2C_Master::Stop ()
Referenced by IMU::ResetDevices().
int I2C_Master::testack (uint8_t ID)
ErrorType I2C_Master::WigglePin (uint8_t cnt, uint8_t pinSel, uint8_t otherState)
Referenced by IMU::FailRecovery().
ErrorType I2C_Master::Write (uint8_t ID, uint8_t * Data, uint8_t nBytes)
void I2C_Master::WriteHandler ()
ErrorType I2C_Master::WriteRead (uint8_t ID, uint8_t * wrData, uint8_t nWriteBytes, uint8_t nReadBytes)
Referenced by IMU::RdAsync(), and IMU::WrAsync().
ErrorType I2C_Master::WriteReadSync (uint8_t ID, uint8_t * wrData, uint8_t nWriteBytes, uint8_t nReadBytes)
Referenced by IMU::Rd().
ErrorType I2C_Master::WriteSync (uint8_t ID, uint8_t * Data, uint8_t nBytes)
Referenced by IMU::Wr().
Member Data Documentation
bool I2C_Master::_bEnabled [private]
Definition at line 51 of file I2C_Master.h.
uint8_t I2C_Master::_DeviceID [private]
Definition at line 58 of file I2C_Master.h.
uint8_t I2C_Master::_IDList[128] [private]
Definition at line 73 of file I2C_Master.h.
uint8_t I2C_Master::_idScanCurrent [private]
Definition at line 72 of file I2C_Master.h.
uint8_t I2C_Master::_nBytesRead [private]
Definition at line 62 of file I2C_Master.h.
uint8_t I2C_Master::_nBytesWritten [private]
Definition at line 59 of file I2C_Master.h.
uint8_t I2C_Master::_nReadBytes [private]
Definition at line 61 of file I2C_Master.h.
uint8_t I2C_Master::_nWriteBytes [private]
Definition at line 60 of file I2C_Master.h.
I2CNotify* I2C_Master::_pNotifyClient [private]
Definition at line 55 of file I2C_Master.h.
void* I2C_Master::_pReserved [private]
Definition at line 54 of file I2C_Master.h.
uint8_t I2C_Master::_rdBufferLen [private]
Definition at line 67 of file I2C_Master.h.
uint8_t* I2C_Master::_ReadData [private]
Definition at line 66 of file I2C_Master.h.
DriverResult I2C_Master::_Result [private]
Definition at line 53 of file I2C_Master.h.
bool I2C_Master::_ScanComplete [private]
Definition at line 74 of file I2C_Master.h.
DriverState I2C_Master::_State [private]
Definition at line 52 of file I2C_Master.h.
TWI_t* I2C_Master::_twi [private]
Definition at line 49 of file I2C_Master.h.
Referenced by IsIdle().
PORT_t* I2C_Master::_twiPort [private]
Definition at line 50 of file I2C_Master.h.
uint8_t I2C_Master::_wrBufferLen [private]
Definition at line 65 of file I2C_Master.h.
uint8_t* I2C_Master::_WriteData [private]
Definition at line 64 of file I2C_Master.h.
The documentation for this class was generated from the following file:
I2C_Master.h