GyroAccGlove: IMU Class Reference
IMU Class Reference
#include <IMU.h>
Classes
struct regWrite
Public Member Functions
IMU (I2C_Master *pMas)
IMU (I2C_Master *pMas, uint8_t gID, uint8_t aID)
Constructor for a single IMU I2C Channel.
IMU (I2C_Master *pMas, uint8_t gID, uint8_t aID, uint8_t gID2, uint8_t aID2)
Constructor for a double IMU I2C Channel.
void QueryChannels ()
void SetDebugPort (DebugPort *pPort)
void SetDebugPort2 (DebugPort *pPort)
virtual void Reset ()
virtual void SampleRate (uint16_t)
virtual int Setup ()
virtual int Start ()
virtual int Stop ()
virtual int ForceStartStop ()
virtual bool Busy ()
virtual void ResetTimer ()
virtual void UseGyro (bool bEnable)
virtual void NextIMU (IMUBase *pNext)
virtual int BeginRead ()
virtual bool DataReady ()
virtual uint8_t * GetPacketData (uint8_t *)
virtual void CheckIDs (HardwareSerial *pSerial)
virtual void ResetDevices ()
void SetTimer (TimerCntr *pTimer)
void SetTimerPeriod ()
virtual void I2CWriteDone ()
virtual void I2CReadDone ()
virtual void I2CBusError ()
virtual void I2CArbLost ()
virtual void I2CNack ()
void FailRecovery ()
Interrupt Handlers
These handlers receive interupts from the Timer class. We registered to received these calls with the Notify function. In some cases we might have 2 or more objects that will send us interrupt notifications, in this case we give each object an ID that is passed back so that we know which one caused the interrupt.
For the IMUManager, there is only a single Timer, so the ID is always 0.
virtual void err (uint8_t id)
Timer Error - ignored.
virtual void ovf (uint8_t id)
virtual void ccx (uint8_t id, uint8_t idx)
Timer Capture Compare - not used.
Protected Member Functions
void Run ()
int StartTransaction ()
void ProcessTransaction ()
int Configure (uint8_t idx)
int Wr (uint8_t ID, uint8_t addr, uint8_t data)
int Rd (uint8_t ID, uint8_t addr, uint8_t cnt, uint8_t *pData)
int WrAsync (uint8_t ID, uint8_t addr, uint8_t data)
int RdAsync (uint8_t ID, uint8_t addr, uint8_t cnt)
void ReadWord (uint16_t *pData)
void StoreGyroData (uint8_t idx)
void StoreAccData (uint8_t idx)
void PushData (uint8_t idx)
Push the data in the temporary buffer onto the appropriate fifo.
void SetState (StateType s)
void MarkPos (PosType p)
void ResetBusyTime ()
bool BusyTimeout ()
void ResetFailStats ()
Private Types
enum StateType {
sIdle = 0, sConfigure = 1, sConfigured = 2, sWait = 5,
sReadGyro1 = 8, sReadAcc1 = 9, sReadGyro2 = 10, sReadAcc2 = 11,
sErrRecover = 12
}
enum PosType {
pStart = 0, pRun = 1, pWriteDn = 2, pReadDn = 3,
pNack = 4, pBusErr = 5, pArbLost = 6, pSetup = 7
}
enum FailType { fNone = 0, fNack = 1, fBusErr = 2, fArbLost = 3 }
enum ProcessType { ptTimer, ptI2CWrite, ptI2CRead, ptI2CNack }
typedef enum IMU::StateType StateType
typedef enum IMU::PosType PosType
typedef enum IMU::FailType FailType
typedef struct IMU::regWrite RegWriteType
Private Attributes
StateType _State
StateType _previousState
FailType _failType
I2C_Master * _pMas
bool _bDualChan
uint8_t _numChans
bool _configOkay [2]
uint8_t _gID [2]
uint8_t _aID [2]
uint8_t _DLPF
uint8_t _FullScale
uint8_t _ClkSel
uint16_t _Rate
bool _bUseGyro
uint8_t _dataBuffer [2][20]
This buffer is used to store data until we push it into the fifo.
bool _bDataReady [2]
TimerCntr * _pTimer
bool _bRun
uint16_t _failCount
uint8_t _nackCount
used for recover logic
bool _bFailDetected
unsigned int _busyWaitTime
DebugPort * _pDBGPort
DebugPort * _pDBGPort2
IMUBase * _pNextIMU
Detailed Description
Definition at line 40 of file IMU.h.
Member Typedef Documentation
typedef enum IMU::FailType IMU::FailType [private]
typedef enum IMU::PosType IMU::PosType [private]
typedef struct IMU::regWrite IMU::RegWriteType [private]
typedef enum IMU::StateType IMU::StateType [private]
Member Enumeration Documentation
enum IMU::FailType [private]
Enumerator:
fNone
fNack
fBusErr
fArbLost
Definition at line 65 of file IMU.h.
{
        fNone           = 0,
        fNack           = 1,
        fBusErr         = 2,
        fArbLost        = 3
    } FailType;
enum IMU::PosType [private]
Enumerator:
pStart
pRun
pWriteDn
pReadDn
pNack
pBusErr
pArbLost
pSetup
Definition at line 54 of file IMU.h.
{
        pStart          = 0,
        pRun            = 1,
        pWriteDn        = 2,
        pReadDn         = 3,
        pNack           = 4,
        pBusErr         = 5,
        pArbLost        = 6,
        pSetup          = 7
    } PosType;
enum IMU::ProcessType [private]
Enumerator:
ptTimer
ptI2CWrite
ptI2CRead
ptI2CNack
Definition at line 78 of file IMU.h.
                  {
        ptTimer,
        ptI2CWrite,
        ptI2CRead,
        ptI2CNack
    } ProcessType;
enum IMU::StateType [private]
Enumerator:
sIdle
sConfigure
sConfigured
sWait
sReadGyro1
sReadAcc1
sReadGyro2
sReadAcc2
sErrRecover
Definition at line 42 of file IMU.h.
{
        sIdle           = 0,
        sConfigure      = 1,
        sConfigured     = 2,
        sWait           = 5,
        sReadGyro1      = 8,
        sReadAcc1       = 9,
        sReadGyro2      = 10,
        sReadAcc2       = 11,
        sErrRecover     = 12
    } StateType;
Constructor & Destructor Documentation
IMU::IMU (I2C_Master * pMas)
Constructor for an auto-query channel Init fifos for dual channel
Definition at line 20 of file IMU.cpp.
References _aID, _bDataReady, _bDualChan, _bRun, _bUseGyro, _busyWaitTime, _ClkSel, _DLPF, _failType, _FullScale, _gID, _numChans, _pDBGPort, _pDBGPort2, _pMas, _pNextIMU, _previousState, _pTimer, _Rate, _State, fNone, I2C_Master::NotifyMe(), QueryChannels(), ResetFailStats(), and sIdle.
{
    _pNextIMU       = 0;
    _gID[0]         = 0;
    _aID[0]         = 0;
    _gID[1]         = 0;
    _aID[1]         = 0;
    _bDualChan      = false;
    _numChans       = 0;
    _pMas           = pMas;
    _DLPF           = 0x1;
    _FullScale      = 0x1;
    _ClkSel         = 0x1;
    _Rate           = 10;
    _State          = sIdle;
    _previousState  = sIdle;
    _failType       = fNone;
    _bRun           = false;
    _busyWaitTime   = 0;
    _bDataReady[0]  = false;
    _bDataReady[1]  = false;
    ResetFailStats();
    _pDBGPort       = 0;
    _pDBGPort2      = 0;
    _pNextIMU       = 0;
    _pTimer         = 0;
    _bUseGyro       = false;
    _pMas->NotifyMe(this);
    QueryChannels();
}
IMU::IMU (I2C_Master * pMas, uint8_t gID, uint8_t aID)
Constructor for a single IMU I2C Channel.
Definition at line 53 of file IMU.cpp.
References _aID, _bDualChan, _bRun, _bUseGyro, _ClkSel, _DLPF, _FullScale, _gID, _numChans, _pDBGPort, _pDBGPort2, _pMas, _pNextIMU, _pTimer, _Rate, _State, I2C_Master::NotifyMe(), ResetFailStats(), and sIdle.
{
    _pNextIMU   = 0;
    _gID[0]     = gID;
    _aID[0]     = aID;
    _bDualChan  = false;
    _numChans   = 1;
    _pMas       = pMas;
    _DLPF       = 0x1;
    _FullScale  = 0x1;
    _ClkSel     = 0x1;
    _Rate       = 10;
    _State      = sIdle;
    _bRun       = false;
    _pMas->NotifyMe(this);
    _pDBGPort   = 0;
    _pDBGPort2  = 0;
    _pTimer     = 0;
    ResetFailStats();
    _bUseGyro   = false;
}
IMU::IMU (I2C_Master * pMas, uint8_t gID, uint8_t aID, uint8_t gID2, uint8_t aID2)
Constructor for a double IMU I2C Channel.
Definition at line 76 of file IMU.cpp.
References _aID, _bDualChan, _bRun, _bUseGyro, _ClkSel, _DLPF, _FullScale, _gID, _numChans, _pDBGPort, _pDBGPort2, _pMas, _pNextIMU, _pTimer, _Rate, _State, I2C_Master::NotifyMe(), ResetFailStats(), and sIdle.
{
    _pNextIMU   = 0;
    _gID[0]     = gID;
    _aID[0]     = aID;
    _gID[1]     = gID2;
    _aID[1]     = aID2;
    _bDualChan  = true;
    _numChans   = 2;
    _pMas       = pMas;
    _DLPF       = 0x1;
    _FullScale  = 0x1;
    _ClkSel     = 0x1;
    _Rate       = 10;
    _State      = sIdle;
    _bRun       = false;
    _pMas->NotifyMe(this);
    _pDBGPort   = 0;
    _pDBGPort2  = 0;
    _pTimer     = 0;
    ResetFailStats();
    _bUseGyro   = false;
}
Member Function Documentation
int IMU::BeginRead () [virtual]
Implements IMUBase.
Definition at line 108 of file IMU.cpp.
References _pNextIMU, _State, IMUBase::BeginRead(), Run(), and sWait.
{
    if (_State == sWait) {
        Run();
    } else {
        if (_pNextIMU) {
            return _pNextIMU->BeginRead();
        }
    }
    return 0;
}
bool IMU::Busy () [virtual]
Implements IMUBase.
Definition at line 277 of file IMU.cpp.
References _State, and sIdle.
{
    return _State != sIdle;
}
bool IMU::BusyTimeout () [inline, protected]
Definition at line 195 of file IMU.h.
References _busyWaitTime.
Referenced by Run().
    {
        return ((millis() - _busyWaitTime) > 2);
    }
void IMU::ccx (uint8_t id, uint8_t idx) [virtual]
Timer Capture Compare - not used.
Implements TimerNotify.
Definition at line 752 of file IMU.cpp.
{
}
void IMU::CheckIDs (HardwareSerial * pSerial) [virtual]
Implements IMUBase.
Definition at line 651 of file IMU.cpp.
References _aID, _gID, _numChans, _pMas, buffer, I2C_Master::CheckID(), Print::print(), and Wr().
{
    char buffer[50];
    for (int x=0;x<_numChans;x++) {
        int retc = _pMas->CheckID(_gID[x]);
        if (retc == 0) {
            sprintf(buffer,"Gyro%d (0x%x):Ack.\n",x,_gID[x]);
            pSerial->print(buffer);
        } else {
            sprintf(buffer,"Gyro%d (0x%x):NAck (%d).\n",x,_gID[x],retc);
            pSerial->print(buffer);
        }
        Wr(_gID[x], 0x3D, 0x8);
        retc = _pMas->CheckID(_aID[x]);
        if (retc == 0) {
            sprintf(buffer,"Acc%d (0x%x):Ack.\n",x,_aID[x]);
            pSerial->print(buffer);
        } else {
            sprintf(buffer,"Acc%d (0x%x):NAck (%d).\n",x,_aID[x],retc);
            pSerial->print(buffer);
        }
    }
}
int IMU::Configure (uint8_t idx) [protected]
Configure the Gyro and Accelerometer device. The input parameter selects the first or second channel. Build an array of RegWrite types so that I can check the return code of each write to insure they all pass.
Definition at line 803 of file IMU.cpp.
References _aID, _ClkSel, _DLPF, _FullScale, _gID, _Rate, ResetBusyTime(), and Wr().
Referenced by Setup().
{
    // Value for the sensor register
    uint16_t gval = 1000/_Rate;
    gval = gval - 1;
    int retc;
    RegWriteType    config[] = {
    //    // Turn on pass-through
        { _gID[idx], 0x3D, 0x0F },
    //
    //    // Init the Accelerometer.
        { _aID[idx], 0x20, 0x37},
        { _aID[idx], 0x21, 0x0},
        { _aID[idx], 0x22, 0x0},
        { _aID[idx], 0x23, 0x80 | 0x40},
        { _aID[idx], 0x24, 0x00},
    //
    //    // Set offsets to zero
        { _gID[idx], 0x0C, 0x00},
        { _gID[idx], 0x0D, 0x00},
        { _gID[idx], 0x0E, 0x00},
        { _gID[idx], 0x0F, 0x00},
        { _gID[idx], 0x10, 0x00},
        { _gID[idx], 0x11, 0x00},
    //
    //    // Configure registers.
        { _gID[idx], 0x12, 0xff},                     // Enable all outputs to to the fifo
        { _gID[idx], 0x13, 0x00},
    //    { _gID[idx], 0x14, _aID[idx] >> 1},             // Set slave address of ACC
        { _gID[idx], 0x15, gval},                     // Set sample rate
        { _gID[idx], 0x16, _DLPF | _FullScale << 3},
        { _gID[idx], 0x17, 0x00},
    //    { _gID[idx], 0x18, 0x80 | 0x28},              // Set burst address for Accelerometer, enable auto addr increment.
        { _gID[idx], 0x3E, _ClkSel},
    };
    uint8_t nItems = sizeof(config)/sizeof(RegWriteType);
    for (int idx = 0;idx <nItems;idx++) {
        retc = Wr(config[idx].ID,
            config[idx].Addr,
            config[idx].Data);
        ResetBusyTime();
        if (retc < 0) {
            return retc; // _configOkay will be false;
        }
    }
    return 0;
}
bool IMU::DataReady () [virtual]
Implements IMUBase.
Definition at line 564 of file IMU.cpp.
References _bDataReady, _bDualChan, and _numChans.
{
    if (_numChans == 0) return true;
    bool bReady = false;
    cli();
    if (_bDualChan) {
        bReady =  _bDataReady[0] && _bDataReady[1];
    } else {
        bReady =  _bDataReady[0];
    }
    sei();
    return bReady;
}
void IMU::err (uint8_t id) [virtual]
Timer Error - ignored.
Implements TimerNotify.
Definition at line 738 of file IMU.cpp.
{
}
void IMU::FailRecovery ()
Called after we handle a Nack, Bus Error or ArbLost Attempt to fix something, then return to the previous state and give it another go. We will basically keep doing this forever until the Manager says stop. All error or fail recovery goes through here.. I have finally gotten things cleaned up enough so that I have a central location for error attempts.
Definition at line 398 of file IMU.cpp.
References _failCount, _failType, _nackCount, _pMas, _previousState, fArbLost, fBusErr, fNack, fNone, Reset(), SetState(), StartTransaction(), and I2C_Master::WigglePin().
Referenced by I2CArbLost(), I2CBusError(), and I2CNack().
{
    switch(_failType) {
    case fNone:
        break;
    case fNack:
        if (_nackCount <7) {
            _pMas->WigglePin(10, 0,1);
        } else if (_nackCount < 10) {
            Reset();
            _pMas->WigglePin(10,0,1);
        }
        SetState(_previousState);
        break;
    case fBusErr:
        if (_failCount < 5) {
            Reset();
        }
        SetState(_previousState);
        break;
    case fArbLost:
        if (_failCount < 5) {
            Reset();
        }
        SetState(_previousState);
        break;
    }
    StartTransaction();
}
int IMU::ForceStartStop () [virtual]
Implements IMUBase.
Definition at line 165 of file IMU.cpp.
References _pMas, and I2C_Master::ForceStartStop().
{
    return _pMas->ForceStartStop();
}
uint8_t * IMU::GetPacketData (uint8_t * pData) [virtual]
Retrieve packet data from the stored packets. If no packet data exists, this function will fill the data pointer with null data - this way any host software can continue, even if data is bad.
Implements IMUBase.
Definition at line 603 of file IMU.cpp.
References _bDataReady, _bDualChan, _dataBuffer, _failType, _numChans, _State, fNack, and sIdle.
{
    if (_numChans == 0) return pData;
    cli();
    *pData++ = 0xa5;
    *pData++ = 0x5a;
    if (_State == sIdle) {
        if (_failType == fNack) {
            memset(pData,'N',IMUPacket::PacketLen);
        } else {
            memset(pData,'I',IMUPacket::PacketLen);
        }
        pData += IMUPacket::PacketLen;
    } else if (_bDataReady[0] == true) {
        memcpy(pData,&_dataBuffer[0][0],IMUPacket::PacketLen);
        _bDataReady[0] = false;
        pData += IMUPacket::PacketLen;
    } else {
        memset(pData,0,IMUPacket::PacketLen);
        pData += IMUPacket::PacketLen;
    }
    if (_bDualChan) {
        *pData++ = 0xa5;
        *pData++ = 0x5a;
        if (_State == sIdle) {
            if (_failType == fNack) {
                memset(pData,'N',IMUPacket::PacketLen);
            } else {
                memset(pData,'I',IMUPacket::PacketLen);
            }
            pData += IMUPacket::PacketLen;
        } else if (_bDataReady[1] == true) {
            memcpy(pData,&_dataBuffer[1][0],IMUPacket::PacketLen);
            _bDataReady[1] = false;
            pData += IMUPacket::PacketLen;
        } else {
            memset(pData,0,IMUPacket::PacketLen);
            pData += IMUPacket::PacketLen;
        }
    }
    sei();
    return pData;
}
void IMU::I2CArbLost () [virtual]
This occurs if the Arbitration is lost. If the I2C is in master mode, and it detects that it cannot control the state of the data line, i.e. it wants to set a HIGH but the line stays low, then this error occurs.
For a first pass, I am going to just try and return to Wait state - this way the timer will take back over and re-try some operation.
I temporarily set this to ErrRecover and then delay. If I am re-starting, then I will go right back, but I will at least trigger the Logic Analyzer
Implements I2CNotify.
Definition at line 534 of file IMU.cpp.
References _bFailDetected, _bRun, _failCount, _failType, _pDBGPort2, _previousState, FailRecovery(), fArbLost, pArbLost, pBusErr, ResetBusyTime(), sErrRecover, SetState(), and StartTransaction().
{
    if (_bRun == false) return;
    ResetBusyTime();
    {
        Mark marker(_pDBGPort2,pBusErr);
        _delay_us(3);
    }
    Mark marker(_pDBGPort2,pArbLost);
    _bFailDetected = true;
    ++_failCount;
    _failType = fArbLost;
    SetState(sErrRecover);
    _delay_us(5);
    if (_failCount > 10) {
        FailRecovery();
    } else {
        SetState(_previousState);
        StartTransaction();
    }
}
void IMU::I2CBusError () [virtual]
Called by I2C Master when a Bus error occurs. This means some non-I2C compliant event occured. Normally, this is going to mean that some glitch occured on the I2C Bus.
For a first pass, I am going to just try and return to Wait state - this way the timer will take back over and re-try some operation.
I temporarily set this to ErrRecover and then delay. If I am re-starting, then I will go right back, but I will at least trigger the Logic Analyzer
Implements I2CNotify.
Definition at line 499 of file IMU.cpp.
References _bFailDetected, _bRun, _failCount, _failType, _pDBGPort2, _previousState, FailRecovery(), fBusErr, pBusErr, ResetBusyTime(), sErrRecover, SetState(), and StartTransaction().
{
    if (_bRun == false) return;
    ResetBusyTime();
    {
        Mark marker(_pDBGPort2,pBusErr);
        _delay_us(3);
    }
    Mark marker(_pDBGPort2,pBusErr);
    _bFailDetected = true;
    ++_failCount;
    _failType = fBusErr;
    SetState(sErrRecover);
    _delay_us(5);
    if (_failCount > 10) {
        FailRecovery();
    } else {
        SetState(_previousState);
        StartTransaction();
    }
}
void IMU::I2CNack () [virtual]
Called by the I2C Master if we get a NAck. Current idea is the repeat the current command until it works since I am seeing that sometimes "Nacks" are temporary So a retry is best. Other types of failures may indicate a need for more desperate action - but those will probably be BusError or Arb Lost commands.
I temporarily set this to ErrRecover and then delay. If I am re-starting, then I will go right back, but I will at least trigger the Logic Analyzer
Re-start the same transaction.
Retry the current transaction until we are sure it won't work.
Keep failing.. just stop.
Implements I2CNotify.
Definition at line 463 of file IMU.cpp.
References _bRun, _failType, _nackCount, _pDBGPort2, _previousState, FailRecovery(), fNack, pBusErr, pNack, ResetBusyTime(), sErrRecover, SetState(), StartTransaction(), and Stop().
{
    if (_bRun == false) return;
    ResetBusyTime();
    {
        Mark marker(_pDBGPort2,pBusErr);
        _delay_us(3);
    }
    Mark marker(_pDBGPort2,pNack);
    ++_nackCount;
    SetState(sErrRecover);
    _delay_us(5);
    if (_nackCount < 5) {
        SetState(_previousState);
        StartTransaction();
    } else if (_nackCount < 10) {
        _failType = fNack;
        FailRecovery();
    } else {
        Stop();
    }
}
void IMU::I2CReadDone () [virtual]
Called be the master when the read is complete. Requires registration Expected Context: Med Lvl I2C Int.
Implements I2CNotify.
Definition at line 446 of file IMU.cpp.
References _bRun, _pDBGPort2, pReadDn, ProcessTransaction(), ResetBusyTime(), and ResetFailStats().
{
    if (_bRun == false) return;
    Mark marker(_pDBGPort2,pReadDn);
    ResetBusyTime();
    ResetFailStats();
    ProcessTransaction();
}
void IMU::I2CWriteDone () [virtual]
Called by the Master when the write is complete. Requires registration Expected Context: Med Lvl I2C Int.
Implements I2CNotify.
Definition at line 432 of file IMU.cpp.
References _bRun, _pDBGPort2, ProcessTransaction(), pWriteDn, ResetBusyTime(), and ResetFailStats().
{
    if (_bRun == false) return;
    Mark marker(_pDBGPort2,pWriteDn);
    ResetBusyTime();
    ResetFailStats();
    ProcessTransaction();
}
void IMU::MarkPos (PosType p) [inline, protected]
Definition at line 185 of file IMU.h.
References _pDBGPort2.
    {
        if (_pDBGPort2) _pDBGPort2->SetState((uint8_t) p);
    }
void IMU::NextIMU (IMUBase * pNext) [virtual]
Implements IMUBase.
Definition at line 103 of file IMU.cpp.
References _pNextIMU.
{
    _pNextIMU = pNext;
}
void IMU::ovf (uint8_t id) [virtual]
Timer Overflow Interrupt. Overflow fires when the timer reaches the top period value. This is setup to fire when we get a timer tick, with a default rate of 500us IMUManager has only one Timer so the ID is not needed.
Implements TimerNotify.
Definition at line 746 of file IMU.cpp.
References Run().
{
    Run();
}
void IMU::ProcessTransaction () [protected]
Called when an Asynchronous I2C operation succeeds. Switch on the state and perform the next appropriate action.
Start the next transaction.
Definition at line 348 of file IMU.cpp.
References _bDualChan, _bUseGyro, _pNextIMU, _State, IMUBase::BeginRead(), PushData(), SetState(), sReadAcc1, sReadAcc2, sReadGyro1, sReadGyro2, StartTransaction(), StoreAccData(), StoreGyroData(), and sWait.
Referenced by I2CReadDone(), and I2CWriteDone().
{
    switch(_State) {
        case sReadGyro1:
            StoreGyroData(1);
            SetState(sReadAcc1);
            break;
        case sReadAcc1:
            StoreAccData(1);
            PushData(1);
            if (_bDualChan) {
                if (_bUseGyro) {
                    SetState(sReadGyro2);
                } else {
                    SetState(sReadAcc2);
                }
            } else {
                SetState(sWait);
                if (_pNextIMU) {
                    _pNextIMU->BeginRead();
                }
            }
            break;
        case sReadGyro2:
            StoreGyroData(2);
            SetState(sReadAcc2);
            break;
        case sReadAcc2:
            StoreAccData(2);
            PushData(2);
            SetState(sWait);
            if (_pNextIMU) {
                _pNextIMU->BeginRead();
            }
            break;
        default:
            break;
    }
    StartTransaction();
}
void IMU::PushData (uint8_t idx) [protected]
Push the data in the temporary buffer onto the appropriate fifo.
Definition at line 594 of file IMU.cpp.
References _bDataReady.
Referenced by ProcessTransaction().
{
    _bDataReady[idx-1] = true;
}
void IMU::QueryChannels ()
Definition at line 120 of file IMU.cpp.
References _aID, _bDualChan, _gID, _numChans, _pMas, and I2C_Master::CheckID().
Referenced by IMU().
{
    _numChans = 0;
    _bDualChan = 0;
    // Check the first, lower ID.
    int retc = _pMas->CheckID(0xD2);
    if (retc == 0) {
        _gID[_numChans] = 0xD2;
        _aID[_numChans] = 0x32; // Always high bit.
        _numChans++;
    }
    retc = _pMas->CheckID(0xD0);
    if (retc == 0) {
        _gID[_numChans] = 0xD0;
        _aID[_numChans] = 0x30; // Always low bit.
        _numChans++;
    }
    if (_numChans > 1) {
        _bDualChan = true;
    }
}
int IMU::Rd (uint8_t ID, uint8_t addr, uint8_t cnt, uint8_t * pData) [protected]
Definition at line 766 of file IMU.cpp.
References _pMas, I2C_Master::ReadData(), and I2C_Master::WriteReadSync().
{
    // Only a single write, the address, then read data.
    int retc = _pMas->WriteReadSync(ID, &addr, 1, cnt);
    if ( retc < 0 ) {
        return retc;
    }
    return _pMas->ReadData(pData,cnt);
}
int IMU::RdAsync (uint8_t ID, uint8_t addr, uint8_t cnt) [protected]
Definition at line 786 of file IMU.cpp.
References _pMas, and I2C_Master::WriteRead().
Referenced by StartTransaction().
{
    // Only a single write, the address, then read data.
    return _pMas->WriteRead(ID, &addr, 1, cnt);
}
void IMU::ReadWord (uint16_t * pData) [protected]
Definition at line 792 of file IMU.cpp.
References _pMas, buffer, and I2C_Master::ReadData().
{
    static uint8_t buffer[2];
    _pMas->ReadData(&buffer[0],2);
    *pData = (buffer[0] << 8 | buffer[1]);
}
void IMU::Reset () [virtual]
Implements IMUBase.
Definition at line 153 of file IMU.cpp.
References _pMas, I2C_Master::begin(), I2C_Master::end(), and I2C_Master::NotifyMe().
Referenced by FailRecovery(), and Run().
{
    _pMas->end();
    _pMas->begin(400e3);
    _pMas->NotifyMe(this);
}
void IMU::ResetBusyTime () [inline, protected]
Definition at line 190 of file IMU.h.
References _busyWaitTime.
Referenced by Configure(), I2CArbLost(), I2CBusError(), I2CNack(), I2CReadDone(), I2CWriteDone(), and StartTransaction().
    {
        _busyWaitTime = millis();
    }
void IMU::ResetDevices () [virtual]
Implements IMUBase.
Definition at line 160 of file IMU.cpp.
References _pMas, and I2C_Master::Stop().
{
    _pMas->Stop();
}
void IMU::ResetFailStats () [inline, protected]
Definition at line 200 of file IMU.h.
References _bFailDetected, _failCount, _failType, _nackCount, and fNone.
Referenced by I2CReadDone(), I2CWriteDone(), IMU(), Setup(), and Start().
    {
        _bFailDetected      = false;
        _nackCount          = 0;
        _failCount          = 0;
        _failType           = fNone;
    }
void IMU::ResetTimer () [virtual]
Reset the counter value. The master uses this to get all of the timers operating at the same time.
Implements IMUBase.
Definition at line 702 of file IMU.cpp.
References _pTimer, and TimerCntr::Counter().
Referenced by Start().
{
    if (_pTimer) _pTimer->Counter(0);
}
void IMU::Run () [protected]
Called by the Timer function periodically. Many of the operations are chainged, meaning the completion of one I2C operation, indicated by an I2C Write or Read interrupt, starts the next operation in the chain. The chain checks the fifo lengths of both fifos, then reads the data if there is any. If there is no data yet, then the state machine enters the sWait state and the next timer will initiate the chain again. Expected Context: Low Lvl Timer
Do nothing while the I2C Master is busy, the master is in the process of some operation. If the master gets hung for some reason, then we will reset and set the state to the sWait state to just start over.
This block only does something in the wait state. Hopefully the rest of the logic, all driven by I2C timeouts, will keep things moving through the other states. Perhaps I should have some sort of state change timeout, as long as we are in the run mode.
Definition at line 290 of file IMU.cpp.
References _bRun, _bUseGyro, _pDBGPort2, _pMas, _State, I2C_Master::busy(), BusyTimeout(), pRun, Reset(), SetState(), sReadAcc1, sReadGyro1, StartTransaction(), and sWait.
Referenced by BeginRead(), and ovf().
{
    if (_bRun == false) return;
    Mark marker(_pDBGPort2,pRun);
    if (_pMas->busy() && BusyTimeout()) {
        Reset();
        SetState(sWait);
    }
    switch(_State) {
    case sWait:
        if (_bUseGyro) {
            SetState(sReadGyro1);
        } else {
            SetState(sReadAcc1);
        }
        StartTransaction();
        break;
    default:
        break;
    }
}
void IMU::SampleRate (uint16_t rate) [virtual]
Implements IMUBase.
Definition at line 170 of file IMU.cpp.
References _Rate, Print::print(), and SetTimerPeriod().
{
    // Range Limit the rate.
    if (rate < 10) {
        _Rate = 10;
    } else if (rate > 200) {
        _Rate = 200;
    } else {
        _Rate = rate;
    }
    uint16_t gval = 1000/rate;
    gval = gval - 1;
    if (pdbgserial) pdbgserial->print("Set Rate on IMU\n");
    SetTimerPeriod();
}
void IMU::SetDebugPort (DebugPort * pPort)
Definition at line 143 of file IMU.cpp.
References _pDBGPort.
Referenced by main().
{
    _pDBGPort = pPort;
}
void IMU::SetDebugPort2 (DebugPort * pPort)
Definition at line 148 of file IMU.cpp.
References _pDBGPort2.
Referenced by main().
{
    _pDBGPort2 = pPort;
}
void IMU::SetState (StateType s) [inline, protected]
Definition at line 178 of file IMU.h.
References _pDBGPort, _previousState, and _State.
Referenced by FailRecovery(), I2CArbLost(), I2CBusError(), I2CNack(), ProcessTransaction(), Run(), Setup(), Start(), and Stop().
    {
        _previousState = _State;
        _State = s;
        if (_pDBGPort) _pDBGPort->SetState((uint8_t)_State);
    }
void IMU::SetTimer (TimerCntr * pTimer)
Set Timer object to use for the main timer tick. This timer needs to be fast enough to send off packets at the rate configured. So, if 200Hz is the rate, then this timer must run at 1 500us rate, etc. The default will be to run at 500us, then the timer can be slowed down if a slower rate is used, just to avoid as much overhead. The CPU Clock runs at 32Mhz, so the main timer clock is running at 32/64 or 500us period. Timer set to same interrupt level as the I2C so that those interrupts won't ever stomp on each other.
This will be 2us period
Definition at line 685 of file IMU.cpp.
References _pTimer, TimerCntr::CCEnable(), TimerCntr::ClkSel(), TimerCntr::EventSetup(), TimerCntr::IntLvlA(), TimerCntr::IntLvlB(), TimerCntr::Notify(), SetTimerPeriod(), and TimerCntr::WaveformGenMode().
{
    _pTimer = pTimer;
    _pTimer->ClkSel(TC_CLKSEL_DIV64_gc);
    SetTimerPeriod();
    _pTimer->CCEnable(0);
    _pTimer->WaveformGenMode(TC_WGMODE_NORMAL_gc);
    _pTimer->EventSetup(TC_EVACT_OFF_gc,TC_EVSEL_OFF_gc);
    _pTimer->IntLvlA(0,1);
    _pTimer->IntLvlB(0);
    _pTimer->Notify(this,0);
}
void IMU::SetTimerPeriod ()
Definition at line 707 of file IMU.cpp.
References _pTimer, _Rate, and TimerCntr::Period().
Referenced by SampleRate(), and SetTimer().
{
    // Adjust the timer function to fire 5X faster
    // than the rate. At 200Hz, this will be 2Khz or
    // every 500us.
    // We set the timer to go off 5 times per IMU period.
    // This should range from 20ms for 10Hz, and 1 ms for 200
    // **** NoFifo
    // Set timer to fire at the rate.
    //unsigned long timerTicks = 100000/_Rate;
    unsigned long timerTicks = 500000/_Rate;
    if (timerTicks > 65000) {
        timerTicks = 65000;
    }
    if (_pTimer) _pTimer->Period(timerTicks);
}
int IMU::Setup () [virtual]
Perform the configuration on the connected IMUs This should be done separately from the loop since this process takes time and we do not want the fifos to be too far out of step. Expected Context: Main
Implements IMUBase.
Definition at line 194 of file IMU.cpp.
References _bRun, _numChans, _pDBGPort2, _State, Configure(), Print::print(), pSetup, ResetFailStats(), sConfigure, sConfigured, SetState(), and sIdle.
Referenced by Start().
{
    if (_numChans == 0) return 0;
    _bRun = false;
    Mark marker(_pDBGPort2,pSetup);
    if (_State != sIdle) {
        if (pdbgserial)
            pdbgserial->print("IMU Already Running.\n");
        return 0; // Already running
    }
    ResetFailStats(); // inline in header
    SetState(sConfigure); // Inline in header
    // Start the process with Configure
    for (int x=0; x<_numChans;x++) {
        if (pdbgserial)
            pdbgserial->print("Configuring IMU\n");
        int retc = Configure(x);
        if (retc < 0 ) {
            // Try reset mechanisms - none of which have
            // been found that work properly yet.
            SetState(sIdle);
            if (pdbgserial)
                pdbgserial->print("IMU Configure Failed.");
            return retc;
        }
    }
    SetState(sConfigured);
    if (pdbgserial)
        pdbgserial->print("IMU Configured.\n");
    return 0;
}
int IMU::Start () [virtual]
Start the reading process running. Run the Setup function which will do asynchronous writes to all of the registers. Setup the run variables and then set our state to reset the fifo lengths then get going. Generally the master will call all of the Setup functions first so the asynchronous Writes there won't be an issue. Expected Context: Main
Implements IMUBase.
Definition at line 239 of file IMU.cpp.
References _bDataReady, _bRun, _numChans, _pDBGPort2, _State, pWriteDn, ResetFailStats(), ResetTimer(), sConfigured, SetState(), Setup(), and sWait.
{
    if (_numChans == 0) return 0;
    Mark marker(_pDBGPort2,pWriteDn);
    int retc;
    if (_State != sConfigured) {
        retc = Setup();
        if (retc < 0) {
            return retc;
        }
    }
    cli();
    ResetTimer();
    SetState(sWait);
    ResetFailStats();
    _bDataReady[0] = false;
    _bDataReady[1] = false;
    _bRun = true;
    sei();
    return 0;
}
int IMU::StartTransaction () [protected]
Definition at line 323 of file IMU.cpp.
References _aID, _gID, _State, RdAsync(), ResetBusyTime(), sReadAcc1, sReadAcc2, sReadGyro1, and sReadGyro2.
Referenced by FailRecovery(), I2CArbLost(), I2CBusError(), I2CNack(), ProcessTransaction(), and Run().
{
    int retc = 0;
    switch(_State) {
    case sReadGyro1:
        RdAsync(_gID[0], 0x1B, 8);
        break;
    case sReadAcc1:
        RdAsync(_aID[0], 0x80 | 0x28, 6);
        break;
    case sReadGyro2:
        RdAsync(_gID[1], 0x1B, 8);
        break;
    case sReadAcc2:
        RdAsync(_aID[1], 0x80 | 0x28, 6);
        break;
    default:
        break;
    }
    ResetBusyTime();
    return retc;
}
int IMU::Stop () [virtual]
Force the state to Idle. We need to consider how this works with iterrupts, but this should only be called from main, below interrupt level, so I think it is okay.
Implements IMUBase.
Definition at line 268 of file IMU.cpp.
References _bRun, SetState(), and sIdle.
Referenced by I2CNack().
{
    cli();
    _bRun = false;
    SetState(sIdle);
    sei();
    return 0;
}
void IMU::StoreAccData (uint8_t idx) [protected]
Add the accelerometer data to the buffer I have the index there in case I need it later..
Definition at line 588 of file IMU.cpp.
References _dataBuffer, _pMas, and I2C_Master::ReadData().
Referenced by ProcessTransaction().
{
    _pMas->ReadData(&_dataBuffer[idx-1][8],6);
}
void IMU::StoreGyroData (uint8_t idx) [protected]
Store the gyro read data while I get the Accelerometer data I have the index there in case I need it later..
Definition at line 581 of file IMU.cpp.
References _dataBuffer, _pMas, and I2C_Master::ReadData().
Referenced by ProcessTransaction().
{
    _pMas->ReadData(&_dataBuffer[idx-1][0],8);
}
virtual void IMU::UseGyro (bool bEnable) [inline, virtual]
Implements IMUBase.
Definition at line 137 of file IMU.h.
References _bUseGyro.
{ _bUseGyro = bEnable; };
int IMU::Wr (uint8_t ID, uint8_t addr, uint8_t data) [protected]
Definition at line 758 of file IMU.cpp.
References _pMas, and I2C_Master::WriteSync().
Referenced by CheckIDs(), and Configure().
{
    static uint8_t  bytes[2];
    bytes[0] = addr;
    bytes[1] = data;
    return _pMas->WriteSync(ID, &bytes[0],2);
}
int IMU::WrAsync (uint8_t ID, uint8_t addr, uint8_t data) [protected]
Definition at line 776 of file IMU.cpp.
References _pMas, buffer, Print::print(), and I2C_Master::WriteRead().
{
    static uint8_t  bytes[2];
    bytes[0] = addr;
    bytes[1] = data;
    sprintf(buffer,"WrAsync to %d\n",ID);
    if (pdbgserial) pdbgserial->print(buffer);
    return _pMas->WriteRead(ID, &bytes[0],2,0);
}
Member Data Documentation
uint8_t IMU::_aID[2] [private]
Definition at line 94 of file IMU.h.
Referenced by CheckIDs(), Configure(), IMU(), QueryChannels(), and StartTransaction().
bool IMU::_bDataReady[2] [private]
Definition at line 104 of file IMU.h.
Referenced by DataReady(), GetPacketData(), IMU(), PushData(), and Start().
bool IMU::_bDualChan [private]
Definition at line 90 of file IMU.h.
Referenced by DataReady(), GetPacketData(), IMU(), ProcessTransaction(), and QueryChannels().
bool IMU::_bFailDetected [private]
Definition at line 110 of file IMU.h.
Referenced by I2CArbLost(), I2CBusError(), and ResetFailStats().
bool IMU::_bRun [private]
Definition at line 107 of file IMU.h.
Referenced by I2CArbLost(), I2CBusError(), I2CNack(), I2CReadDone(), I2CWriteDone(), IMU(), Run(), Setup(), Start(), and Stop().
bool IMU::_bUseGyro [private]
Definition at line 100 of file IMU.h.
Referenced by IMU(), ProcessTransaction(), Run(), and UseGyro().
unsigned int IMU::_busyWaitTime [private]
Definition at line 111 of file IMU.h.
Referenced by BusyTimeout(), IMU(), and ResetBusyTime().
uint8_t IMU::_ClkSel [private]
Definition at line 97 of file IMU.h.
Referenced by Configure(), and IMU().
bool IMU::_configOkay[2] [private]
Definition at line 92 of file IMU.h.
uint8_t IMU::_dataBuffer[2][20] [private]
This buffer is used to store data until we push it into the fifo.
Definition at line 103 of file IMU.h.
Referenced by GetPacketData(), StoreAccData(), and StoreGyroData().
uint8_t IMU::_DLPF [private]
Definition at line 95 of file IMU.h.
Referenced by Configure(), and IMU().
uint16_t IMU::_failCount [private]
Definition at line 108 of file IMU.h.
Referenced by FailRecovery(), I2CArbLost(), I2CBusError(), and ResetFailStats().
FailType IMU::_failType [private]
Definition at line 87 of file IMU.h.
Referenced by FailRecovery(), GetPacketData(), I2CArbLost(), I2CBusError(), I2CNack(), IMU(), and ResetFailStats().
uint8_t IMU::_FullScale [private]
Definition at line 96 of file IMU.h.
Referenced by Configure(), and IMU().
uint8_t IMU::_gID[2] [private]
Definition at line 93 of file IMU.h.
Referenced by CheckIDs(), Configure(), IMU(), QueryChannels(), and StartTransaction().
uint8_t IMU::_nackCount [private]
used for recover logic
Definition at line 109 of file IMU.h.
Referenced by FailRecovery(), I2CNack(), and ResetFailStats().
uint8_t IMU::_numChans [private]
Definition at line 91 of file IMU.h.
Referenced by CheckIDs(), DataReady(), GetPacketData(), IMU(), QueryChannels(), Setup(), and Start().
DebugPort* IMU::_pDBGPort [private]
Definition at line 112 of file IMU.h.
Referenced by IMU(), SetDebugPort(), and SetState().
DebugPort* IMU::_pDBGPort2 [private]
Definition at line 113 of file IMU.h.
Referenced by I2CArbLost(), I2CBusError(), I2CNack(), I2CReadDone(), I2CWriteDone(), IMU(), MarkPos(), Run(), SetDebugPort2(), Setup(), and Start().
I2C_Master* IMU::_pMas [private]
Definition at line 89 of file IMU.h.
Referenced by CheckIDs(), FailRecovery(), ForceStartStop(), IMU(), QueryChannels(), Rd(), RdAsync(), ReadWord(), Reset(), ResetDevices(), Run(), StoreAccData(), StoreGyroData(), Wr(), and WrAsync().
IMUBase* IMU::_pNextIMU [private]
Definition at line 114 of file IMU.h.
Referenced by BeginRead(), IMU(), NextIMU(), and ProcessTransaction().
StateType IMU::_previousState [private]
Definition at line 86 of file IMU.h.
Referenced by FailRecovery(), I2CArbLost(), I2CBusError(), I2CNack(), IMU(), and SetState().
TimerCntr* IMU::_pTimer [private]
Definition at line 106 of file IMU.h.
Referenced by IMU(), ResetTimer(), SetTimer(), and SetTimerPeriod().
uint16_t IMU::_Rate [private]
Definition at line 98 of file IMU.h.
Referenced by Configure(), IMU(), SampleRate(), and SetTimerPeriod().
StateType IMU::_State [private]
Definition at line 85 of file IMU.h.
Referenced by BeginRead(), Busy(), GetPacketData(), IMU(), ProcessTransaction(), Run(), SetState(), Setup(), Start(), and StartTransaction().
The documentation for this class was generated from the following files:
IMU.h
IMU.cpp