GyroAccGlove: TimerCntr Class Reference
TimerCntr Class Reference
#include <TimerCntr.h>
Public Member Functions
TimerCntr (TC0_t *pTC)
TimerCntr (TC1_t *pTC)
~TimerCntr ()
void Notify (TimerNotify *pClient, uint8_t id)
void ovf ()
void err ()
void ccx (uint8_t idx)
void ClkSel (TC_CLKSEL_t clksel)
Set the clock source for this timer in CTRLA.
void CCEnable (uint8_t mask)
void WaveformGenMode (TC_WGMODE_t wgmode)
void EventSetup (TC_EVACT_t act, TC_EVSEL_t src)
void IntLvlA (uint8_t errlvl, uint8_t ovflvl)
void IntLvlB (uint8_t val)
void Counter (uint16_t newVal)
uint16_t Counter ()
void Period (uint16_t newPer)
uint16_t Period ()
void SetRate (uint32_t rateHz)
void CCReg (uint8_t idx, uint16_t newVal)
uint16_t CCReg (uint8_t idx)
Private Attributes
TC0_t * _pTC
bool _bTC1
TimerNotify * _pNotifyClient
uint8_t _pNotifyClientID
Detailed Description
Definition at line 13 of file TimerCntr.h.
Constructor & Destructor Documentation
TimerCntr::TimerCntr (TC0_t * pTC)
Definition at line 116 of file TimerCntr.cpp.
References _bTC1, _pNotifyClient, _pNotifyClientID, _pTC, and SetPointer().
{
    _pTC = pTC;
    _bTC1 = false;
    _pNotifyClient = 0;
    _pNotifyClientID = 0;
    SetPointer(pTC,this);
}
TimerCntr::TimerCntr (TC1_t * pTC)
Definition at line 125 of file TimerCntr.cpp.
References _bTC1, _pNotifyClient, _pNotifyClientID, _pTC, and SetPointer().
{
    _pTC = (TC0_t*)pTC;
    _bTC1 = true;
    _pNotifyClient = 0;
    _pNotifyClientID = 0;
    SetPointer(pTC,this);
}
TimerCntr::~TimerCntr ()
Definition at line 134 of file TimerCntr.cpp.
References _bTC1, _pTC, and SetPointer().
{
    if (_bTC1) {
        SetPointer((TC1_t*)_pTC,0);
    } else {
        SetPointer(_pTC,0);
    }
}
Member Function Documentation
void TimerCntr::CCEnable (uint8_t mask)
Set the state of the 4 CCxEN bits in CTRLB. The 4 lower bits of mask will enable D, C, B or A if set to 1
Definition at line 150 of file TimerCntr.cpp.
References _pTC.
Referenced by IMU::SetTimer().
{
    _pTC->CTRLB = ((_pTC->CTRLB & 0x0F) | (mask << 4));
}
void TimerCntr::CCReg (uint8_t idx, uint16_t newVal)
Definition at line 200 of file TimerCntr.cpp.
References _bTC1, and _pTC.
{
    if (idx == 0) {
        _pTC->CCA = newVal;
    } else if (idx == 1) {
        _pTC->CCB = newVal;
    } else if (!_bTC1 && idx == 2) {
        _pTC->CCC = newVal;
    } else if (!_bTC1 && idx == 3) {
        _pTC->CCD = newVal;
    }
}
uint16_t TimerCntr::CCReg (uint8_t idx)
Definition at line 213 of file TimerCntr.cpp.
References _bTC1, and _pTC.
{
    if (idx == 0) {
        return _pTC->CCA;
    } else if (idx == 1) {
        return _pTC->CCB;
    } else if (!_bTC1 && idx == 2) {
        return _pTC->CCC;
    } else if (!_bTC1 && idx == 3) {
        return _pTC->CCD;
    }
    return 0;
}
void TimerCntr::ccx (uint8_t idx)
Definition at line 245 of file TimerCntr.cpp.
References _pNotifyClient, _pNotifyClientID, and TimerNotify::ccx().
{
    if (_pNotifyClient)
        _pNotifyClient->ccx(_pNotifyClientID,idx);
}
void TimerCntr::ClkSel (TC_CLKSEL_t clksel)
Set the clock source for this timer in CTRLA.
Definition at line 144 of file TimerCntr.cpp.
References _pTC.
Referenced by IMU::SetTimer().
{
    _pTC->CTRLA = clksel;
}
void TimerCntr::Counter (uint16_t newVal)
Definition at line 178 of file TimerCntr.cpp.
References _pTC.
Referenced by IMU::ResetTimer().
{
    _pTC->CNT = newVal;
}
uint16_t TimerCntr::Counter ()
Definition at line 183 of file TimerCntr.cpp.
References _pTC.
{
    return _pTC->CNT;
}
void TimerCntr::err ()
Definition at line 233 of file TimerCntr.cpp.
References _pNotifyClient, _pNotifyClientID, and TimerNotify::err().
{
    if (_pNotifyClient)
        _pNotifyClient->err(_pNotifyClientID);
}
void TimerCntr::EventSetup (TC_EVACT_t act, TC_EVSEL_t src)
Definition at line 162 of file TimerCntr.cpp.
References _pTC.
Referenced by IMU::SetTimer().
{
    _pTC->CTRLD = act | src;
}
void TimerCntr::IntLvlA (uint8_t errlvl, uint8_t ovflvl)
Definition at line 168 of file TimerCntr.cpp.
References _pTC.
Referenced by IMU::SetTimer().
{
    _pTC->INTCTRLA = (errlvl & 0x3) << 2 | (ovflvl & 0x3);
}
void TimerCntr::IntLvlB (uint8_t val)
Definition at line 173 of file TimerCntr.cpp.
References _pTC.
Referenced by IMU::SetTimer().
{
    _pTC->INTCTRLB = val;
}
void TimerCntr::Notify (TimerNotify * pClient, uint8_t id)
Definition at line 227 of file TimerCntr.cpp.
References _pNotifyClient, and _pNotifyClientID.
Referenced by IMU::SetTimer().
{
    _pNotifyClient = pClient;
    _pNotifyClientID = id;
}
void TimerCntr::ovf ()
Definition at line 239 of file TimerCntr.cpp.
References _pNotifyClient, _pNotifyClientID, and TimerNotify::ovf().
{
    if (_pNotifyClient)
        _pNotifyClient->ovf(_pNotifyClientID);
}
void TimerCntr::Period (uint16_t newPer)
Definition at line 189 of file TimerCntr.cpp.
References _pTC.
Referenced by IMU::SetTimerPeriod().
{
    _pTC->PER = newVal;
}
uint16_t TimerCntr::Period ()
Definition at line 194 of file TimerCntr.cpp.
References _pTC.
{
    return _pTC->PER;
}
void TimerCntr::SetRate (uint32_t rateHz)
Definition at line 251 of file TimerCntr.cpp.
{
    //add an auto prescaler using 32 bit array
}
void TimerCntr::WaveformGenMode (TC_WGMODE_t wgmode)
Set the Waveform generator mode. Normal disables waveform generation.
Definition at line 156 of file TimerCntr.cpp.
References _pTC.
Referenced by IMU::SetTimer().
{
    _pTC->CTRLB = ((_pTC->CTRLB & 0xF0) | wgmode);
}
Member Data Documentation
bool TimerCntr::_bTC1 [private]
Definition at line 19 of file TimerCntr.h.
Referenced by CCReg(), TimerCntr(), and ~TimerCntr().
TimerNotify* TimerCntr::_pNotifyClient [private]
Definition at line 20 of file TimerCntr.h.
Referenced by ccx(), err(), Notify(), ovf(), and TimerCntr().
uint8_t TimerCntr::_pNotifyClientID [private]
Definition at line 21 of file TimerCntr.h.
Referenced by ccx(), err(), Notify(), ovf(), and TimerCntr().
TC0_t* TimerCntr::_pTC [private]
Definition at line 18 of file TimerCntr.h.
Referenced by CCEnable(), CCReg(), ClkSel(), Counter(), EventSetup(), IntLvlA(), IntLvlB(), Period(), TimerCntr(), WaveformGenMode(), and ~TimerCntr().
The documentation for this class was generated from the following files:
TimerCntr.h
TimerCntr.cpp