GyroAccGlove: IMUDual Class Reference
IMUDual Class Reference
#include <IMU.h>
Public Member Functions
IMUDual (I2C_Master *pMas, uint8_t gIDa, uint8_t aIDa, uint8_t gIDb, uint8_t aIDb)
virtual int Configure ()
virtual void Reset ()
virtual void SampleRate (uint16_t)
virtual int StartRead ()
virtual bool ReadDone ()
virtual bool Busy ()
virtual bool FifoReady ()
virtual void InitFifo ()
virtual bool FifoInitialized ()
virtual void I2CWriteDone ()
virtual void I2CReadDone ()
virtual uint8_t * ReadData (uint8_t *)
virtual void ShowRegs ()
virtual void CheckIDs (HardwareSerial *pSerial)
virtual void ResetDevices ()
virtual void FifoReset ()
virtual void EnableFifos ()
virtual void SendStop ()
Protected Member Functions
int StartRead (uint8_t idx)
void SaveFifoData (uint8_t idx)
int Wr (uint8_t ID, uint8_t addr, uint8_t data)
int Rd (uint8_t ID, uint8_t addr, uint8_t cnt, uint8_t *pData)
Private Types
enum StateType { sIdle, sRead1, sRead2, sReadDone }
typedef enum IMUDual::StateType StateType
Private Attributes
StateType _State
I2C_Master * _pMas
uint8_t _gID [2]
uint8_t _aID [2]
uint8_t _DLPF
uint8_t _FullScale
uint8_t _ClkSel
uint16_t _Rate
bool _bInTransaction
uint8_t _fifoData [2][20]
bool _bFifosInitialized
Detailed Description
Definition at line 84 of file IMU.h.
Member Typedef Documentation
typedef enum IMUDual::StateType IMUDual::StateType [private]
Member Enumeration Documentation
enum IMUDual::StateType [private]
Enumerator:
sIdle
sRead1
sRead2
sReadDone
Definition at line 87 of file IMU.h.
{
        sIdle, sRead1, sRead2, sReadDone
    } StateType;
Constructor & Destructor Documentation
IMUDual::IMUDual (I2C_Master * pMas, uint8_t gIDa, uint8_t aIDa, uint8_t gIDb, uint8_t aIDb)
Definition at line 15 of file IMUDual.cpp.
References _aID, _ClkSel, _DLPF, _FullScale, _gID, _pMas, _Rate, _State, and sIdle.
{
    _gID[0]     = gIDa;
    _aID[0]     = aIDa;
    _gID[1]     = gIDb;
    _aID[1]     = aIDb;
    _pMas       = pMas;
    _DLPF       = 0x1;
    _FullScale  = 0x1;
    _ClkSel     = 0x1;
    _Rate       = 10;
    _State      = sIdle;
    _pMas->NotifyMe(this);
}
Member Function Documentation
bool IMUDual::Busy () [virtual]
Implements IMUBase.
Definition at line 109 of file IMUDual.cpp.
References _State, and sIdle.
{
    return _State != sIdle;
}
void IMUDual::CheckIDs (HardwareSerial * pSerial) [virtual]
Implements IMUBase.
Definition at line 279 of file IMUDual.cpp.
References _aID, _gID, _pMas, buffer, Print::print(), and Wr().
{
    char buffer[50];
    for (int x=0;x<2;x++) {
        int retc = _pMas->CheckID(_gID[x]);
        if (retc == 0) {
            pSerial->print("Gyro:Ack.\n");
        } else {
            sprintf(buffer,"Gyro:NAck (%d).\n",retc);
            pSerial->print(buffer);
        }
        Wr(_gID[x], 0x3D, 0x8);
        retc = _pMas->CheckID(_aID[x]);
        if (retc == 0) {
            pSerial->print("Acc:Ack.\n");
        } else {
            sprintf(buffer,"Acc:NAck (%d).\n",retc);
            pSerial->print(buffer);
        }
    }
}
int IMUDual::Configure () [virtual]
Implements IMUBase.
Definition at line 60 of file IMUDual.cpp.
References _aID, _ClkSel, _DLPF, _FullScale, _gID, _Rate, and Wr().
{
    uint16_t gval = 1000/_Rate;
    gval = gval - 1;
    for (int x=0;x<2;x++) {
        // set IMU3000 Passthrough
        Wr(_gID[x], 0x3D, 0x8);
        // Setup the LIS331
        Wr(_aID[x], 0x20, 0x37);
        Wr(_aID[x], 0x21, 0x0);
        Wr(_aID[x], 0x22, 0x0);
        Wr(_aID[x], 0x23, 0x80 | 0x40);
        Wr(_aID[x], 0x24, 0x00);
        // Configure the IMU3000
        uint8_t addr;
        for (addr = 0x12;addr < 0x18;addr++) {
            Wr(_gID[x],addr,0x0);
        }
        Wr(_gID[x], 0x12,0xff);         // Enable all outputs to to the fifo
        Wr(_gID[x], 0x13,0x00);
        Wr(_gID[x], 0x14,_aID[x] >> 1);    // Set slave address of ACC
        //Wr(_gID[x], 0x15,4);            // Set sample rate to 200Hz
        Wr(_gID[x], 0x15,gval);            // Set sample rate to 10Hz for testing.
        Wr(_gID[x], 0x16,_DLPF | _FullScale << 3);
        Wr(_gID[x], 0x18,0x80 | 0x28);  // Set burst address for Accelerometer, enable auto addr increment.
        Wr(_gID[x], 0x3E,_ClkSel);
        // Turn off passthrough
        Wr(_gID[x], 0x3D,0x28);
    }
        return 0;
}
void IMUDual::EnableFifos () [virtual]
Implements IMUBase.
Definition at line 316 of file IMUDual.cpp.
References _gID, and Wr().
{
    for (int x=0;x<2;x++) {
        Wr(_gID[x], 0x3D, 0x62);
    }
}
bool IMUDual::FifoInitialized () [virtual]
Implements IMUBase.
Definition at line 225 of file IMUDual.cpp.
References _bFifosInitialized, _gID, FifoReady(), Print::print(), and Rd().
{
    bool    bReady = _bFifosInitialized;
    if (!bReady) {
        if (FifoReady()) {
            uint8_t  data[14];
            Rd(_gID[0], 0x3C, 14,&data[0]);
            Rd(_gID[1], 0x3C, 14,&data[0]);
            bReady = true;
            _bFifosInitialized = true;
            pdbgserial->print("Fifo Initialized\n");
        }
    }
    return bReady;
}
bool IMUDual::FifoReady () [virtual]
Implements IMUBase.
Definition at line 176 of file IMUDual.cpp.
References _gID, and Rd().
Referenced by FifoInitialized().
{
    uint16_t    fifoCnt[2];
    uint8_t     rdData[2];
    bool        bReady = false;
    // Not checking return, assume both work!
    Rd(_gID[0],0x3A, 2, &rdData[0]);
    fifoCnt[0] = (rdData[0] & 0x3) << 8 | rdData[1];
    Rd(_gID[1],0x3A, 2, &rdData[0]);
    fifoCnt[1] = (rdData[0] & 0x3) << 8 | rdData[1];
    //sprintf(buffer,"FifoCnt: %x %x\n",fifoCnt[0], fifoCnt[1]);
    //pdbgserial->print(buffer);
    //_bFifosInitialized ?
    //    bReady = (fifoCnt[0] > 15 && fifoCnt[1] > 15) :
    //    bReady = (fifoCnt[0] > 13 && fifoCnt[1] > 13);
    bReady = (fifoCnt[0] > 15 && fifoCnt[1] > 15);
    return bReady;
}
void IMUDual::FifoReset () [virtual]
Implements IMUBase.
Definition at line 306 of file IMUDual.cpp.
References _gID, Rd(), and Wr().
{
    uint8_t rdData;
    for (int x=0;x<2;x++) {
        Wr(_gID[x], 0x3D, 0x1f); // Turn off fifo, reset.
        Rd(_gID[x], 0x1A, 1, &rdData);
    }
}
void IMUDual::I2CReadDone () [virtual]
Definition at line 251 of file IMUDual.cpp.
References _State, Print::print(), SaveFifoData(), sIdle, sRead1, sRead2, sReadDone, and StartRead().
{
    switch(_State) {
    case sRead1:
        // The first part of the read finished, start part 2
        // and set the state.
        SaveFifoData(0);
        _State = sRead2;
        if (StartRead(1) == 0) {
            pdbgserial->print("IMUDual State => sRead2\n");
        } else {
            _State = sIdle; // not sure what else to do???
            pdbgserial->print("Bad Start, going to Idle\n");
        }
        break;
    case sRead2:
        // Both reads are done now...
        _State = sReadDone;
        SaveFifoData(1);
        pdbgserial->print("IMUDual State => sReadDone\n");
        break;
    default:
        break;
    }
}
void IMUDual::I2CWriteDone () [virtual]
Definition at line 243 of file IMUDual.cpp.
{
    // We don't really do anything here.. we do not have
    // any asynchronous write routines.
}
void IMUDual::InitFifo () [virtual]
Implements IMUBase.
Definition at line 203 of file IMUDual.cpp.
References _bFifosInitialized, _gID, buffer, Print::print(), Rd(), and Wr().
{
    Wr(_gID[0], 0x3D, 0x62);
    Wr(_gID[1], 0x3D, 0x62);
    _bFifosInitialized = false;
#ifdef DEBUG
    // This was for debug.. not needed normally.
    uint8_t rddata[2];
    Rd(_gID[0], 0x3D, 1,&rddata[0]);
    Rd(_gID[1], 0x3D, 1,&rddata[1]);
    sprintf(buffer,"Fifo Init: 0x3D is 0x%x 0x%x\n",
        rddata[0],rddata[1]);
    pdbgserial->print(buffer);
#endif
}
int IMUDual::Rd (uint8_t ID, uint8_t addr, uint8_t cnt, uint8_t * pData) [protected]
Definition at line 40 of file IMUDual.cpp.
References _pMas.
Referenced by FifoInitialized(), FifoReady(), FifoReset(), and InitFifo().
{
    // Only a single write, the address, then read data.
    int retc = _pMas->WriteReadSync(ID, &addr, 1, cnt);
    if ( retc < 0 ) {
        return retc;
    }
    return _pMas->ReadData(pData,cnt);
}
uint8_t * IMUDual::ReadData (uint8_t * pData) [virtual]
Implements IMUBase.
Definition at line 148 of file IMUDual.cpp.
References _fifoData.
{
    //*pData++ = 14;
    *pData++ = 0xa5;
    *pData++ = 0x5a;
    memcpy(pData,&_fifoData[0][0],18);
    pData += 18;
    //*pData++ = 14;
    *pData++ = 0xa5;
    *pData++ = 0x5a;
    memcpy(pData,&_fifoData[1][0],18);
    pData += 18;
    return pData;
}
bool IMUDual::ReadDone () [virtual]
Implements IMUBase.
Definition at line 164 of file IMUDual.cpp.
References _State, and sReadDone.
{
    if (_State == sReadDone) {
        return true;
    }
    return false;
}
void IMUDual::Reset () [virtual]
Implements IMUBase.
Definition at line 97 of file IMUDual.cpp.
References _pMas, _State, and sIdle.
{
    _pMas->end();
    _pMas->begin(400e3);
    _pMas->NotifyMe(this);
    _State      = sIdle;
}
void IMUDual::ResetDevices () [virtual]
Implements IMUBase.
Definition at line 301 of file IMUDual.cpp.
References _pMas.
{
    _pMas->Stop();
}
void IMUDual::SampleRate (uint16_t rate) [virtual]
Implements IMUBase.
Definition at line 51 of file IMUDual.cpp.
References _gID, _Rate, and Wr().
{
    _Rate = rate;
    uint16_t gval = 1000/rate;
    gval = gval - 1;
    Wr(_gID[0], 0x15,gval);
    Wr(_gID[1], 0x15,gval);
}
void IMUDual::SaveFifoData (uint8_t idx) [protected]
Definition at line 143 of file IMUDual.cpp.
References _fifoData, and _pMas.
Referenced by I2CReadDone().
{
    _pMas->ReadData(&_fifoData[idx][0],18);
}
void IMUDual::SendStop () [virtual]
Implements IMUBase.
Definition at line 324 of file IMUDual.cpp.
References _pMas.
{
    _pMas->Stop();
}
void IMUDual::ShowRegs () [virtual]
Implements IMUBase.
Definition at line 105 of file IMUDual.cpp.
{
}
int IMUDual::StartRead () [virtual]
Implements IMUBase.
Definition at line 118 of file IMUDual.cpp.
References _State, Print::print(), sIdle, and sRead1.
Referenced by I2CReadDone().
{
    _State  = sRead1;
    if (StartRead(0) == 0) {
        pdbgserial->print("StartRead Ok\n");
    } else {
        _State = sIdle;
        pdbgserial->print("StartRead Failed\n");
    }
        return 0;
}
int IMUDual::StartRead (uint8_t idx) [protected]
Definition at line 131 of file IMUDual.cpp.
References _gID, and _pMas.
{
    uint8_t addr = 0x3A; // Fifo Data Address.
    int retc = _pMas->WriteRead(_gID[idx], &addr, 1, 18);
    //sprintf(buffer,"StartRead %d\n",idx);
    //pdbgserial->print(buffer);
    return retc;
}
int IMUDual::Wr (uint8_t ID, uint8_t addr, uint8_t data) [protected]
Definition at line 32 of file IMUDual.cpp.
References _pMas.
Referenced by CheckIDs(), Configure(), EnableFifos(), FifoReset(), InitFifo(), and SampleRate().
{
    static uint8_t  bytes[2];
    bytes[0] = addr;
    bytes[1] = data;
    return _pMas->WriteSync(ID, &bytes[0],2);
}
Member Data Documentation
uint8_t IMUDual::_aID[2] [private]
Definition at line 94 of file IMU.h.
Referenced by CheckIDs(), Configure(), and IMUDual().
bool IMUDual::_bFifosInitialized [private]
Definition at line 101 of file IMU.h.
Referenced by FifoInitialized(), and InitFifo().
bool IMUDual::_bInTransaction [private]
Definition at line 99 of file IMU.h.
uint8_t IMUDual::_ClkSel [private]
Definition at line 97 of file IMU.h.
Referenced by Configure(), and IMUDual().
uint8_t IMUDual::_DLPF [private]
Definition at line 95 of file IMU.h.
Referenced by Configure(), and IMUDual().
uint8_t IMUDual::_fifoData[2][20] [private]
Definition at line 100 of file IMU.h.
Referenced by ReadData(), and SaveFifoData().
uint8_t IMUDual::_FullScale [private]
Definition at line 96 of file IMU.h.
Referenced by Configure(), and IMUDual().
uint8_t IMUDual::_gID[2] [private]
Definition at line 93 of file IMU.h.
Referenced by CheckIDs(), Configure(), EnableFifos(), FifoInitialized(), FifoReady(), FifoReset(), IMUDual(), InitFifo(), SampleRate(), and StartRead().
I2C_Master* IMUDual::_pMas [private]
Definition at line 92 of file IMU.h.
Referenced by CheckIDs(), IMUDual(), Rd(), Reset(), ResetDevices(), SaveFifoData(), SendStop(), StartRead(), and Wr().
uint16_t IMUDual::_Rate [private]
Definition at line 98 of file IMU.h.
Referenced by Configure(), IMUDual(), and SampleRate().
StateType IMUDual::_State [private]
Definition at line 90 of file IMU.h.
Referenced by Busy(), I2CReadDone(), IMUDual(), ReadDone(), Reset(), and StartRead().
The documentation for this class was generated from the following files:
IMU.h
IMUDual.cpp