GyroAccGlove: Print Class Reference
Print Class Reference
#include <Print.h>
Public Member Functions
virtual void write (uint8_t)=0
virtual void write (const char *str)
virtual void write (const uint8_t *buffer, size_t size)
void print (const char[])
void print (char, int=BYTE)
void print (unsigned char, int=BYTE)
void print (int, int=DEC)
void print (unsigned int, int=DEC)
void print (long, int=DEC)
void print (unsigned long, int=DEC)
void print (double, int=2)
void println (const char[])
void println (char, int=BYTE)
void println (unsigned char, int=BYTE)
void println (int, int=DEC)
void println (unsigned int, int=DEC)
void println (long, int=DEC)
void println (unsigned long, int=DEC)
void println (double, int=2)
void println (void)
Private Member Functions
void printNumber (unsigned long, uint8_t)
void printFloat (double, uint8_t)
Detailed Description
Definition at line 32 of file Print.h.
Member Function Documentation
void Print::print (const char str[])
Definition at line 45 of file Print.cpp.
References write().
Referenced by CmdProcessor::checkCommands(), IMU::CheckIDs(), FifoTest(), main(), print(), printFloat(), println(), printNumber(), IMU::SampleRate(), IMU::Setup(), and IMU::WrAsync().
{
  write(str);
}
void Print::print (unsigned char b, int base = BYTE)
Definition at line 55 of file Print.cpp.
References print().
{
  print((unsigned long) b, base);
}
void Print::print (int n, int base = DEC)
Definition at line 60 of file Print.cpp.
References print().
{
  print((long) n, base);
}
void Print::print (unsigned int n, int base = DEC)
Definition at line 65 of file Print.cpp.
References print().
{
  print((unsigned long) n, base);
}
void Print::print (long n, int base = DEC)
Definition at line 70 of file Print.cpp.
References print(), printNumber(), and write().
{
  if (base == 0) {
    write(n);
  } else if (base == 10) {
    if (n < 0) {
      print('-');
      n = -n;
    }
    printNumber(n, 10);
  } else {
    printNumber(n, base);
  }
}
void Print::print (char c, int base = BYTE)
Definition at line 50 of file Print.cpp.
References print().
{
  print((long) c, base);
}
void Print::print (unsigned long n, int base = DEC)
Definition at line 85 of file Print.cpp.
References printNumber(), and write().
{
  if (base == 0) write(n);
  else printNumber(n, base);
}
void Print::print (double n, int digits = 2)
Definition at line 91 of file Print.cpp.
References printFloat().
{
  printFloat(n, digits);
}
void Print::printFloat (double number, uint8_t digits) [private]
Definition at line 173 of file Print.cpp.
References print().
Referenced by print().
{
  // Handle negative numbers
  if (number < 0.0)
  {
     print('-');
     number = -number;
  }
  // Round correctly so that print(1.999, 2) prints as "2.00"
  double rounding = 0.5;
  for (uint8_t i=0; i<digits; ++i)
    rounding /= 10.0;
  number += rounding;
  // Extract the integer part of the number and print it
  unsigned long int_part = (unsigned long)number;
  double remainder = number - (double)int_part;
  print(int_part);
  // Print the decimal point, but only if there are digits beyond
  if (digits > 0)
    print(".");
  // Extract digits from the remainder one at a time
  while (digits-- > 0)
  {
    remainder *= 10.0;
    int toPrint = int(remainder);
    print(toPrint);
    remainder -= toPrint;
  }
}
void Print::println (long n, int base = DEC)
Definition at line 132 of file Print.cpp.
References print(), and println().
{
  print(n, base);
  println();
}
void Print::println (void)
Definition at line 96 of file Print.cpp.
References print().
Referenced by println().
{
  print('\r');
  print('\n');
}
void Print::println (unsigned char b, int base = BYTE)
Definition at line 114 of file Print.cpp.
References print(), and println().
{
  print(b, base);
  println();
}
void Print::println (double n, int digits = 2)
Definition at line 144 of file Print.cpp.
References print(), and println().
{
  print(n, digits);
  println();
}
void Print::println (unsigned int n, int base = DEC)
Definition at line 126 of file Print.cpp.
References print(), and println().
{
  print(n, base);
  println();
}
void Print::println (unsigned long n, int base = DEC)
Definition at line 138 of file Print.cpp.
References print(), and println().
{
  print(n, base);
  println();
}
void Print::println (char c, int base = BYTE)
Definition at line 108 of file Print.cpp.
References print(), and println().
{
  print(c, base);
  println();
}
void Print::println (const char c[])
Definition at line 102 of file Print.cpp.
References print(), and println().
{
  print(c);
  println();
}
void Print::println (int n, int base = DEC)
Definition at line 120 of file Print.cpp.
References print(), and println().
{
  print(n, base);
  println();
}
void Print::printNumber (unsigned long n, uint8_t base) [private]
Definition at line 152 of file Print.cpp.
References print().
Referenced by print().
{
  unsigned char buf[8 * sizeof(long)]; // Assumes 8-bit chars.
  unsigned long i = 0;
  if (n == 0) {
    print('0');
    return;
  }
  while (n > 0) {
    buf[i++] = n % base;
    n /= base;
  }
  for (; i > 0; i--)
    print((char) (buf[i - 1] < 10 ?
      '0' + buf[i - 1] :
      'A' + buf[i - 1] - 10));
}
virtual void Print::write (uint8_t) [pure virtual]
Implemented in HardwareSerial.
Referenced by print(), and write().
void Print::write (const char * str) [virtual]
Definition at line 32 of file Print.cpp.
References write().
{
  while (*str)
    write(*str++);
}
void Print::write (const uint8_t * buffer, size_t size) [virtual]
Definition at line 39 of file Print.cpp.
References write().
{
  while (size--)
    write(*buffer++);
}
The documentation for this class was generated from the following files:
Print.h
Print.cpp