GyroAccGlove: Fifo Class Reference
Fifo Class Reference
Fifo Class for unsigned 8 bit values.
#include <fifo.h>
Public Types
typedef uint8_t FifoType
Public Member Functions
Fifo (uint8_t size)
int8_t push (FifoType *)
int8_t pop (FifoType *pData)
uint8_t count ()
bool full ()
Return true if the fifo is full.
bool empty ()
Return true if the fifo is empty.
void clear ()
Clear the fifo by resetting the start and end pointer.
Private Attributes
FifoType * _pdata
FifoType * _start
FifoType * _end
uint8_t _size
Detailed Description
Fifo Class for unsigned 8 bit values.
Construct a fifo and specify the number of elements to store. The fifo constructor will allocate memory for the specified number of values. The Fifo class contains member functions for pusshing, popping and checking the status of the fifo.
Definition at line 16 of file fifo.h.
Member Typedef Documentation
typedef uint8_t Fifo::FifoType
Definition at line 20 of file fifo.h.
Constructor & Destructor Documentation
Fifo::Fifo (uint8_t size)
Construct the fifo object. Allocate memory for the specified number of elements and set the internal value to indicate the size of the fifo. Reset the start and end data points to their clear state. The clear function is called to maintain consitency and insure that clear() always does the right thing.
Definition at line 14 of file fifo.cpp.
References _pdata, _size, and clear().
{
    _size = size;
    _pdata = (FifoType*)malloc(_size * sizeof(FifoType));
    clear();
}
Member Function Documentation
void Fifo::clear ()
Clear the fifo by resetting the start and end pointer.
Definition at line 22 of file fifo.cpp.
References _end, _pdata, and _start.
Referenced by Fifo(), and FifoTest().
{
    _start = _end = _pdata;
}
uint8_t Fifo::count ()
Return the number of elements currently in the fifo if the end and start pointers are the same then the fifo is empty and count == 0. If they differ, then we need to check for wrap-around in order to properly determine the size. In the following examples a = marks empty spots, while an x marks filled spots.
            s                       e
     =======xxxxxxxxxxxxxxxxxxxxxxxxx=======================
In this case end > start, so count is equal to the distance between them or .
            e                       s
     xxxxxxxx=======================xxxxxxxxxxxxxxxxxxxxxxxx
In this case end < start, so data wraps around. The total count is equal to the size of the buffer, minus the number of blank spots, or .
The total number of possible elements that can be stored is size -1, so
Definition at line 50 of file fifo.cpp.
References _end, _size, and _start.
Referenced by FifoTest().
{
    if (_end == _start) return 0;
    if (_end > _start) {
        return _end - _start;
    }
    return _size - (_start - _end);
}
bool Fifo::empty ()
Return true if the fifo is empty.
Definition at line 66 of file fifo.cpp.
References _end, and _start.
Referenced by pop().
{
    return (_start == _end);
}
bool Fifo::full ()
Return true if the fifo is full.
Definition at line 60 of file fifo.cpp.
References _end, _size, and _start.
Referenced by push().
{
    return (_start - _end)  == 1 || (_end - _start) == _size;
}
int8_t Fifo::pop (FifoType * pD)
Remove the top value from the Fifo. We do not have exceptions in this simple C++ implementation, so this function is not able to do anything to indicate that the called tried to pop a value from an empty fifo. In that case, a zero value is returned, which is not unique so the caller will have to insure that pop is never called on an empty fifo.
Definition at line 92 of file fifo.cpp.
References _pdata, _size, _start, and empty().
Referenced by FifoTest().
{
    if (empty()) {
        return -1; // Nothing else to do
    }
    *pD = *(_start++);
    if ((_start - _pdata) > _size) {
        _start = _pdata;
    }
    return 0;
}
int8_t Fifo::push (FifoType * d)
Push a new value onto the fifo. This function returns 0 if the operation succeeds, and a negative value if the operation fails.
Definition at line 74 of file fifo.cpp.
References _end, _pdata, _size, and full().
Referenced by FifoTest().
{
    if (full()) return -1;
    *(_end++) = *d;
    // Wrap the end back to the beginning.
    if ((_end - _pdata) > _size) {
        _end = _pdata;
    }
        return 0;
}
Member Data Documentation
FifoType* Fifo::_end [private]
Definition at line 25 of file fifo.h.
Referenced by clear(), count(), empty(), full(), and push().
FifoType* Fifo::_pdata [private]
Definition at line 23 of file fifo.h.
Referenced by clear(), Fifo(), pop(), and push().
uint8_t Fifo::_size [private]
Definition at line 26 of file fifo.h.
Referenced by count(), Fifo(), full(), pop(), and push().
FifoType* Fifo::_start [private]
Definition at line 24 of file fifo.h.
Referenced by clear(), count(), empty(), full(), and pop().
The documentation for this class was generated from the following files:
fifo.h
fifo.cpp